server:
  port: 8761

spring:
  application:
    name: eureka-server

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411

eureka:
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true